#!/bin/bash
g++ mainTestServo.cpp ../Servo/Servo.cpp ../Frame/Frame.cpp ../ServoEXP/ServoEXP.cpp ../FrameEXP/FrameEXP.cpp ../MVG/MVG.cpp ../Quaternion/Quaternion.cpp ../../VAR/VAR.cpp ../../EXP/EXP.cpp ../../FUNC/FUNC.cpp ../../Operations/Operations.cpp -o testSERVOEXP -lwiringPi -std=c++11 -std=gnu++11
