#!/bin/bash
g++-4.7 mainHAROEXP.cpp ./HARO/HAROLegsEXP.cpp ./HARO/HAROEXP.cpp ./PE/PE.cpp ./Servo/Servo.cpp ./ServoEXP/ServoEXP.cpp ./Frame/Frame.cpp ./FrameEXP/FrameEXP.cpp ./MVG/MVG.cpp ./Quaternion/Quaternion.cpp ./PE/MPU6050/MPU6050.cpp ./PE/RPI/I2Cdev/I2Cdev.cpp -l bcm2835 -l m -lSDL -lSDLmain -lwiringPi -pthread -std=c++0x -o outputHAROEXP
