#!/bin/bash
g++ mainHARO.cpp ./HARO/HAROLegs.cpp ./HARO/HARO.cpp ./PE/PE.cpp ./Servo/Servo.cpp ./Frame/Frame.cpp ./MVG/MVG.cpp ./Quaternion/Quaternion.cpp ./PE/MPU6050/MPU6050.cpp ./PE/RPI/I2Cdev/I2Cdev.cpp -l bcm2835 -l m -lSDL -lSDLmain -lwiringPi -pthread -std=c++0x -o outputHARO
